---
- name: Install & upgrade packages
  hosts: raspberry
  tasks:
    - name: Upgrade all packages
      tags: upgrade
      ansible.builtin.apt:
        upgrade: full
        update_cache: yes
        cache_valid_time: 3600
    - name: Install packages
      ansible.builtin.apt:
        name:
          - nano
          - git
          - wget
          - htop
          - tmux
        cache_valid_time: 3600
        state: present
